// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	C2S_Register_Req
	S2C_Register_Res
	C2S_Login_Req
	S2C_Login_Res
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EMsg int32

const (
	EMsg_C2S_Register_Req_ID EMsg = 1
	EMsg_S2C_Register_Res_ID EMsg = 2
	EMsg_C2S_Login_Req_ID    EMsg = 3
	EMsg_S2C_Login_Res_ID    EMsg = 4
)

var EMsg_name = map[int32]string{
	1: "C2S_Register_Req_ID",
	2: "S2C_Register_Res_ID",
	3: "C2S_Login_Req_ID",
	4: "S2C_Login_Res_ID",
}
var EMsg_value = map[string]int32{
	"C2S_Register_Req_ID": 1,
	"S2C_Register_Res_ID": 2,
	"C2S_Login_Req_ID":    3,
	"S2C_Login_Res_ID":    4,
}

func (x EMsg) Enum() *EMsg {
	p := new(EMsg)
	*p = x
	return p
}
func (x EMsg) String() string {
	return proto.EnumName(EMsg_name, int32(x))
}
func (x *EMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EMsg_value, data, "EMsg")
	if err != nil {
		return err
	}
	*x = EMsg(value)
	return nil
}
func (EMsg) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type C2S_Register_Req struct {
	UserName         *string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_Register_Req) Reset()                    { *m = C2S_Register_Req{} }
func (m *C2S_Register_Req) String() string            { return proto.CompactTextString(m) }
func (*C2S_Register_Req) ProtoMessage()               {}
func (*C2S_Register_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2S_Register_Req) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *C2S_Register_Req) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type S2C_Register_Res struct {
	Result           *bool   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	ErrorCode        *int32  `protobuf:"varint,2,opt,name=errorCode" json:"errorCode,omitempty"`
	ErrorStr         *string `protobuf:"bytes,3,opt,name=errorStr" json:"errorStr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_Register_Res) Reset()                    { *m = S2C_Register_Res{} }
func (m *S2C_Register_Res) String() string            { return proto.CompactTextString(m) }
func (*S2C_Register_Res) ProtoMessage()               {}
func (*S2C_Register_Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2C_Register_Res) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func (m *S2C_Register_Res) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *S2C_Register_Res) GetErrorStr() string {
	if m != nil && m.ErrorStr != nil {
		return *m.ErrorStr
	}
	return ""
}

type C2S_Login_Req struct {
	UserName         *string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2S_Login_Req) Reset()                    { *m = C2S_Login_Req{} }
func (m *C2S_Login_Req) String() string            { return proto.CompactTextString(m) }
func (*C2S_Login_Req) ProtoMessage()               {}
func (*C2S_Login_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *C2S_Login_Req) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *C2S_Login_Req) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type S2C_Login_Res struct {
	Result           *bool   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	ErrorCode        *int32  `protobuf:"varint,2,opt,name=errorCode" json:"errorCode,omitempty"`
	ErrorStr         *string `protobuf:"bytes,3,opt,name=errorStr" json:"errorStr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2C_Login_Res) Reset()                    { *m = S2C_Login_Res{} }
func (m *S2C_Login_Res) String() string            { return proto.CompactTextString(m) }
func (*S2C_Login_Res) ProtoMessage()               {}
func (*S2C_Login_Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *S2C_Login_Res) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func (m *S2C_Login_Res) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *S2C_Login_Res) GetErrorStr() string {
	if m != nil && m.ErrorStr != nil {
		return *m.ErrorStr
	}
	return ""
}

func init() {
	proto.RegisterType((*C2S_Register_Req)(nil), "msg.C2S_Register_Req")
	proto.RegisterType((*S2C_Register_Res)(nil), "msg.S2C_Register_Res")
	proto.RegisterType((*C2S_Login_Req)(nil), "msg.C2S_Login_Req")
	proto.RegisterType((*S2C_Login_Res)(nil), "msg.S2C_Login_Res")
	proto.RegisterEnum("msg.EMsg", EMsg_name, EMsg_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x53, 0xa5, 0x19, 0x28, 0x84, 0x55, 0x6a, 0x10, 0x0f, 0x92, 0x93, 0x78, 0xc8,
	0xa1, 0x3f, 0xc1, 0x28, 0xa2, 0xa8, 0x87, 0xcd, 0x0f, 0x08, 0xc1, 0x0c, 0x4b, 0xa8, 0xbb, 0x5b,
	0x67, 0xb6, 0x88, 0xff, 0x5e, 0x26, 0x31, 0x55, 0x73, 0x95, 0x1e, 0xdf, 0x7b, 0xf0, 0xe6, 0xdb,
	0xb7, 0x90, 0x58, 0x36, 0xc5, 0x96, 0x7c, 0xf0, 0x2a, 0xb6, 0x6c, 0xf2, 0x47, 0x48, 0xcb, 0x75,
	0x55, 0x6b, 0x34, 0x1d, 0x07, 0xa4, 0x5a, 0xe3, 0xbb, 0x3a, 0x87, 0xc5, 0x8e, 0x91, 0x5e, 0x1a,
	0x8b, 0x59, 0x74, 0x19, 0x5d, 0x25, 0x7a, 0xaf, 0x25, 0xdb, 0x36, 0xcc, 0x1f, 0x9e, 0xda, 0x6c,
	0x36, 0x64, 0xa3, 0xce, 0x5b, 0x48, 0xab, 0x75, 0xf9, 0xbb, 0x8b, 0xd5, 0x0a, 0x8e, 0x09, 0x79,
	0xf7, 0x16, 0xfa, 0xa6, 0x85, 0xfe, 0x56, 0xea, 0x02, 0x12, 0x24, 0xf2, 0x54, 0xfa, 0x16, 0xfb,
	0xa2, 0x23, 0xfd, 0x63, 0xc8, 0x95, 0x5e, 0x54, 0x81, 0xb2, 0x78, 0xb8, 0x32, 0xea, 0xfc, 0x1e,
	0x96, 0x42, 0xfc, 0xe4, 0x4d, 0xe7, 0xfe, 0x85, 0xdb, 0xc0, 0x52, 0x70, 0xc7, 0xa2, 0x03, 0xb0,
	0x5e, 0xb7, 0x30, 0xbf, 0x7b, 0x66, 0xa3, 0xce, 0xe0, 0x64, 0xba, 0x72, 0xfd, 0x70, 0x9b, 0x46,
	0x12, 0x4c, 0x27, 0x93, 0x60, 0xa6, 0x4e, 0x87, 0x7f, 0xd9, 0xbf, 0x52, 0xdc, 0x58, 0xdc, 0x3f,
	0xc8, 0xe2, 0xce, 0x6f, 0x32, 0x58, 0xbd, 0x7a, 0x5b, 0x6c, 0xbc, 0x33, 0x9f, 0xa1, 0xd8, 0xa0,
	0x33, 0x9d, 0xc3, 0xc2, 0xb2, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x94, 0x43, 0x71, 0x98, 0xee,
	0x01, 0x00, 0x00,
}
